### ISSUE TITLE
Issue when many incoming messages

### ISSUE THREAD

**Issue by developerfromjokela** [BRUHItsABunny/go-android-firebase#2]
panic: proto.Unmarshal: proto: cannot parse invalid wire-format data

goroutine 39 [running]:
github.com/BRUHItsABunny/go-android-firebase/client.(*MTalkCon).loop(0xc000214240)
	/go/pkg/mod/github.com/!b!r!u!h!its!a!bunny/go-android-firebase@v0.1.0/client/mtalk.go:92 +0x65
created by github.com/BRUHItsABunny/go-android-firebase/client.(*MTalkCon).Connect in goroutine 19
	/go/pkg/mod/github.com/!b!r!u!h!its!a!bunny/go-android-firebase@v0.1.0/client/mtalk.go:84 +0x30a

**Comment by adriancable** [comment]
@developerfromjokela - experiencing the same issue. Did you ever find a resolution?

**Comment by BRUHItsABunny** [comment]
What rate of incoming messages does it take to recreate this?

I haven't been able to recreate this, any help with that will allow me to check it out.

**Comment by adriancable** [comment]
I think the issue is due to TCP packet fragmentation which becomes more likely as packet rate increases. Client would need to buffer and reassemble partial message fragments to avoid this.

**Comment by BRUHItsABunny** [comment]
Not saying that it isn't TCP fragmentation, it very well can be but isn't TCP fragmentation usually handled on the OS TCP stack?

My knowledge on raw TCP isn't very extensive, I will do some more research

**Comment by adriancable** [comment]
I used a bad term. You are right that it is likely not IP fragmentation. Let me be more precise.

In general you cannot assume that when you read data from a socket, you will get exactly one protobuf message. gRPC servers buffer output data: below a low water mark (when total service utilisation is low), the server will combine small consecutive packets into single TCP packets to improve efficiency. Above a high water mark (when total service utilisation is high) the server will split packets to get them onto the wire faster, to reduce pressure on the buffer. This latter situation is what is happening occasionally and causing the panic. But you need to handle cases where you might receive less than one message, one message, or more than one message at a time.

**Comment by developerfromjokela** [comment]
> @developerfromjokela - experiencing the same issue. Did you ever find a resolution?

Not unfortunately, I don't use it because of this issue.

**Comment by developerfromjokela** [comment]
But @BRUHItsABunny it would be nice to fix this issue, my usecase involved receiving many push notifications at the same time in some situations, so quite busy.

**Comment by BRUHItsABunny** [comment]
I recently ran into a similar panic while testing my web push notifications implementation, basically the message was too big to be read by `RawConn.Read` and it would get an EOF prematurely (in my case the buffer we make with the message length still had like 20 0x00 bytes.)
I recently fixed that particular occurrence by using `io.ReadFull` instead. 

![Image](https://github.com/user-attachments/assets/e8c915fe-ca19-469e-ad31-8907011cf6ee)

No problems ever since.

 I have not yet found a case where I receive mixed messages and have to read more than one pb message at the same time. I personally think it's unlikely to happen because usually you would have some kind of framing in place to handle this on the protocol level. For gRPC it does exist on top of http2 frames but this mtalk connection is not actually a gRPC connection rather just a socket that happens to receive protobuf messages (but not rpcs) that were prepended with a tag and length (which on it's own is the basics for "framing" i guess? albeit with a limitation where messages can only be written one at a time. Similar to head of line blocking on http connections prior to http3)

Give it a try on v0.2.0 and see if you are still having issues @developerfromjokela

**Comment by developerfromjokela** [comment]
> I recently ran into a similar panic while testing my web push notifications implementation, basically the message was too big to be read by `io.ReadN` and it would get an EOF prematurely (in my case the buffer we make with the message length still had like 20 0x00 bytes.)
> I recently fixed that particular occurrence by using `io.ReadAll` instead. I have not yet found a case where I receive mixed messages and have to read more than one pb message at the same time. I personally think it's unlikely to happen because usually you would have some kind of framing in place to handle this on the protocol level. For gRPC it does exist on top of http2 frames but this mtalk connection is not actually a gRPC connection rather just a socket that happens to receive protobuf messages (but not rpcs) that were prepended with a tag and length (which on it's own is the basics for "framing" i guess?)
> 
> Give it a try on v0.2.0 and see if you are still having issues @developerfromjokela 

Thx, will try.

**Comment by BRUHItsABunny** [comment]
Thanks, and my apologies for being away for so long.
